### PR TITLE
New hard coded footprints and related documentation

### PR DESCRIPTION
**Pull request by wehrad**
Resulting masks coming soon

### CODE REVIEW

**Comment by mankoff** [comment]
I'll wait for masks to merge this request.

**Comment by wehrad** [comment]
I just created a new request with all the masks.

**Comment by wehrad** [comment]
Could you request changes on this request? I would like to add the last footprint linked to the masks I downloaded without creating a new request. It seems like I can not change my commit without you asking for it.

**Comment by mankoff** [comment]
Just push a new commit on top of the old one, and I think it'll show up here.

**Comment by wehrad** [comment]
It actually didn't ... So I created a new request "new footprints + Beaufort" that contains the changes of this request and the last footprint, all in one.

**Pull request closed without merging**
